[package]
name = "postform-host"
version = "0.1.0"
authors = ["Javier Alvarez <javier.alvarez@allthingsembedded.net>"]
edition = "2018"

[dependencies]
probe-rs = "0.9.0"
probe-rs-rtt = "0.4.0"
structopt = "0.3"
object = "0.22.0"
termion = "1.5.5"
cobs = "0.1.4"

