name: Postform

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cargo_clippy:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Install libusb and libftdi
      run: |
        sudo apt update
        sudo apt install -y libusb-1.0-0-dev libftdi1-dev
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Run cargo fmt check
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check
    - name: Run cargo clippy
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features

  cargo_build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: Javier-varez/google-repo-action@v0.2
      with:
        manifest-url: 'Javier-varez/manifest'
        manifest-group: 'postform'
        checkout-deps: true
    - name: Install libusb and libftdi
      run: |
        sudo apt update
        sudo apt install -y libusb-1.0-0-dev libftdi1-dev
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Run cargo build
      working-directory: postform
      run: cargo build
    - name: Archive binaries
      uses: actions/upload-artifact@v2
      with:
        name: postform_persist
        path: postform/target/debug/postform_persist

  cargo_test:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Install libusb and libftdi
      run: |
        sudo apt update
        sudo apt install -y libusb-1.0-0-dev libftdi1-dev
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Run cargo test
      uses: actions-rs/cargo@v1
      with:
        command: test

  libpostform_build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: Javier-varez/google-repo-action@v0.2
      with:
        manifest-url: 'Javier-varez/manifest'
        manifest-group: 'postform'
        checkout-deps: true
    - name: arm-none-eabi-gcc
      uses: fiam/arm-none-eabi-gcc@v1.0.3
      with:
        release: '9-2020-q2'
    - name: Install bear
      run: sudo apt install bear
    - name: make
      run: make -j
    - name: Archive binaries
      uses: actions/upload-artifact@v2
      with:
        name: format_host
        path: build/targets/format_host

  system_test:
    runs-on: ubuntu-latest
    needs: [ cargo_build, libpostform_build ]

    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Download format_host binary
      uses: actions/download-artifact@v2
      with:
        name: format_host
        path: binaries
    - name: Download postform_persist binary
      uses: actions/download-artifact@v2
      with:
        name: postform_persist
        path: binaries
    - name: Set permissions
      run: chmod +x ./binaries/format_host ./binaries/postform_persist
    - name: Execute format_host
      run: ./binaries/format_host host.log
    - name: Decode log
      run: ./binaries/postform_persist binaries/format_host host.log > actual_log.txt
    - name: Compare translated logs
      run: diff expected_log.txt actual_log.txt
